---
title: "visualization2"
output: github_document
---

```{r}
library(tidyverse)
library(ggridges)
library(patchwork)

knitr::opts_chunk$set(
  fig.width = 6,
  fig.asp = .6,
  out.width = "90%"
)
```

Get the data for plotting 

```{r}
weather_df = 
  rnoaa::meteo_pull_monitors(
    c("USW00094728", "USW00022534", "USS0023B17S"),
    var = c("PRCP", "TMIN", "TMAX"), 
    date_min = "2021-01-01",
    date_max = "2022-12-31") |>
  mutate(
    name = recode(
      id, 
      USW00094728 = "CentralPark_NY", 
      USW00022534 = "Molokai_HI",
      USS0023B17S = "Waterhole_WA"),
    tmin = tmin / 10,
    tmax = tmax / 10) |>
  select(name, id, everything())
```

## Same plot from last time

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs min daily temp in three locations; data from rnoaa"
  ) + 
  scale_x_continuous(
    breaks = c(-15, 0, 15),
    labels = c("-15 C", "0", "15")
  ) + 
  scale_y_continuous(
    position = "right", 
    trans = "sqrt"
  )
```

what about colors
```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs min daily temp in three locations; data from rnoaa"
  )+
  viridis::scale_color_viridis(discrete = TRUE)
```


## Themes

```{r}
weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  labs(
    title = "Temperature plot",
    x = "Min daily temp (Degrees C)",
    y = "Max daily temp",
    color = "Location",
    caption = "Max vs min daily temp in three locations; data from rnoaa"
  )+
  viridis::scale_color_viridis(discrete = TRUE)+
  theme_minimal() +
  theme(legend.position ='bottom')
```

## data argument ...

```{r}
weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_smooth()

nyc_weather_df = 
  weather_df |> 
  filter(name == "CentralPark_NY")

hawaii_weather_df = 
  weather_df |> 
  filter(name == "Molokai_HI")


ggplot(nyc_weather_df, aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_line(data = hawaii_weather_df)
  
```

## `patchwork`

```{r}
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  facet_grid(. ~ name)
```

```{r}
ggp_temp_scatter = 
  weather_df |> 
  ggplot(aes(x = tmin, y = tmax, color = name)) + 
  geom_point(alpha = .5) + 
  theme(legend.position = "none")

ggp_prcp_density = 
  weather_df |> 
  filter(prcp > 25) |> 
  ggplot(aes(x = prcp, fill = name)) + 
  geom_density(alpha = .5) + 
  theme(legend.position = "bottom")

ggp_tmax_date = 
  weather_df |> 
  ggplot(aes(x = date, y = tmax, color = name)) + 
  geom_point() + 
  geom_smooth(se = FALSE) + 
  theme(legend.position = "bottom")

(ggp_temp_scatter + ggp_prcp_density) / ggp_tmax_date
```


## data manipulation

```{r}
weather_df |> 
  mutate(
    name = fct_relevel(name, c('Molokai_Hi', 'CentralPark_NY', 'Waterhole_WA')) 
  ) |> 
  ggplot( aes(x=name, y=tmax)) +
  geom_boxplot()

  weather_df |> 
    mutate(
      name = fct_reorder(name, tmax)
    ) |> 
  ggplot(aes(x=name, y=tmax, color=name))+
    geom_violin()

```

## complicate FAS plot

```{r}
litters_df =
  read_csv('data/FAS_litters.csv') |> 
  janitor:: clean_names() |> 
  seperate(group, into =c('dose', 'day_of_tx'), sep =3)

pups_df =
  litters_df =
  read_csv('data/FAS_pups.csv') |> 
  janitor:: clean_names() 

fas_df =
  left_join(pups_df, litters_df, by = "litter_number")

fas_df |> 
  select(dose, day_of_tx, starts_with("pd")) |> 
  pivot_longer(
    pd_ears:pd_walk, 
    names_to = "outcome", 
    values_to = "pn_day"
  ) |> 
  drop_na() |> 
  mutate(outcome =fct_reorder(outcome, pn_day)) |> 
  ggplot(aes(x=dose, y=pn_day)) +
  geom_violin() +
  facet_grid(day_of_tx-outcome)
```


